### ISSUE TITLE
Set up automatic builds & publishing to PyPI on tag creation

### ISSUE THREAD

**Issue by edgarrmondragon** [MeltanoLabs/tap-mysql#24]
```[tasklist]
### Tasks
- [ ] https://github.com/MeltanoLabs/tap-mysql/issues/25
- [ ] https://github.com/MeltanoLabs/tap-mysql/issues/26
- [ ] https://github.com/MeltanoLabs/tap-mysql/issues/27
- [x] Set up PyPI trusted publisher
```

**Comment by edgarrmondragon** [comment]
Done:

<details><summary>Rule definition</summary>
<p>

```json
{
  "id": 363329,
  "name": "Default Branch",
  "target": "branch",
  "source_type": "Repository",
  "source": "MeltanoLabs/tap-mysql",
  "enforcement": "active",
  "conditions": {
    "ref_name": {
      "exclude": [],
      "include": [
        "~DEFAULT_BRANCH"
      ]
    }
  },
  "rules": [
    {
      "type": "deletion"
    },
    {
      "type": "non_fast_forward"
    },
    {
      "type": "required_linear_history"
    },
    {
      "type": "pull_request",
      "parameters": {
        "required_approving_review_count": 0,
        "dismiss_stale_reviews_on_push": true,
        "require_code_owner_review": false,
        "require_last_push_approval": true,
        "required_review_thread_resolution": true
      }
    }
  ],
  "bypass_actors": [
    {
      "actor_id": 5,
      "actor_type": "RepositoryRole",
      "bypass_mode": "always"
    },
    {
      "actor_id": 1,
      "actor_type": "OrganizationAdmin",
      "bypass_mode": "always"
    }
  ]
}
```

</p>
</details>
